### ISSUE TITLE
2 search terms cause 500 error

### ISSUE THREAD

**Issue by benhammondmusic** [cwverica/quixr#4]
Hi! Fun project; nice work! I was able to search for "mint" and "basil" individually, but when I search for "mint basil" I get a 500 error. I tried "orange juice" to see if it was the presence of a space in the string, but "orange juice" worked.

**Comment by benhammondmusic** [comment]
This was on your heroku deployment, btw

**Comment by cwverica** [comment]
Hey, thanks man!

I can't believe I missed that. I have it set up to say there are no
results, but I guess I missed a connection somewhere.
I'll get on that!

**Comment by cwverica** [comment]
Fixed it. 👍 Thanks Ben, appreciate the 👀
